### ISSUE TITLE
ESLint 9 / Flat config support

### ISSUE THREAD

**Issue by brettz9** [gavinaiken/eslint-plugin-chai-expect-keywords#17]
Hi,

As of ESLint 8, there is now a new format for ESLint config files which requires that plugins follow a specific format. In ESLint 9, this format will be the only one available by default (and other API changes have occurred in ESLint 9 that may affect this plugin).

Info:

1. https://eslint.org/docs/latest/use/configure/configuration-files-new
1. https://eslint.org/blog/2022/08/new-config-system-part-1/
1. https://eslint.org/blog/2022/08/new-config-system-part-2/
1. https://eslint.org/docs/latest/use/configure/migration-guide

Might you update to be compatible with the new format?

Thanks!

**Comment by gavinaiken** [comment]
I'll try to take a look at this in the next week or two

**Comment by gavinaiken** [comment]
I'm working on this now, I expect to have it working next week. There's a similar issue with `eslint-plugin-chai-expect` however...

**Comment by gavinaiken** [comment]
This is now complete in version 3.0.0, published to npm
