### ISSUE TITLE
Recommended config

### ISSUE THREAD

**Issue by brettz9** [gavinaiken/eslint-plugin-chai-expect-keywords#3]
In order to avoid the need for adding to `plugins` and `rules` (and just add `extends: ['plugin:chai-expect-keywords/recommended']`), it'd be nice if the recommended config could be  added with the rule added to it, along with the options `allowSinonChai` and `allowChaiAsPromised` set to `true`.

I could make a PR if this would be desired.

**Comment by gavinaiken** [comment]
PR's happily received, but I can look at addressing these ideas in the next week or so if not

**Comment by brettz9** [comment]
Ok, sure, will see. Are you amenable to updating the devDeps. (which have vulnerabilities), and if you like (possibly to go along with the devDep. updates which may have minimum versions), optionally also adding a minimum Node version accordingly? And adding test coverage via nyc?
